language: java

sudo: true

services:
  - redis-server
  - docker

cache:
  directories:
  - $HOME/.m2
  
install:
  - docker pull orientdb

jdk:
- oraclejdk8

script:
- mvn -f negozio/pom.xml install -Dmaven.javadoc.skip=true -B -V -Pjacoco coveralls:report