language: java

sudo: true

cache:
  directories:
  - $HOME/.m2

install: true

jdk:
- oraclejdk8

script:
- mvn -f negozio/negozio-concreto/pom.xml clean verify -Pjacoco coveralls:report
- mvn -f negozio/negozio-redis/pom.xml clean verify -Pjacoco coveralls:report

