language: java

sudo: true

services:
  - docker

cache:
  directories:
  - $HOME/.m2


before_install: 
  - docker pull redis
  - docker run -p 6379:6379 --rm redis 

jdk:
- oraclejdk8

script:
- mvn -f negozio/pom.xml install -Dmaven.javadoc.skip=true -B -V